# Generated by Django 2.2.11 on 2020-03-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('searching', models.IntegerField(default=0)),
                ('connect', models.IntegerField(default=0)),
            ],
        ),
    ]
