# Generated by Django 2.2.10 on 2020-02-19 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Kitaplar', '0001_initial'),
        ('Kullanicilar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kutuphanem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kitap_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kitaplar.Kitaplar')),
                ('Kullanici_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kullanicilar.Kullanicilar')),
            ],
        ),
    ]
