# Generated by Django 2.2.10 on 2020-02-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kutuphanem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kutuphanem',
            name='Kitap_Id',
            field=models.IntegerField(),
        ),
    ]
