# Generated by Django 2.2.9 on 2020-01-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30, verbose_name='Kullanıcı Adı')),
                ('userSurname', models.CharField(max_length=30)),
            ],
        ),
    ]
