# Generated by Django 2.2.10 on 2020-02-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanicilar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Sifre', models.CharField(max_length=16, verbose_name='Şifre')),
                ('Yetki', models.CharField(default='Musteri', max_length=16, verbose_name='Yetki')),
                ('Ad', models.CharField(max_length=32, verbose_name='Ad')),
                ('Soyad', models.CharField(max_length=32, verbose_name='Soyad')),
                ('Tel', models.CharField(max_length=11, null='True', verbose_name='Telefon')),
            ],
        ),
    ]
